export interface PokemonStatus {
  abilities: Array<any>,
  base_experience: number
  forms: Array<any>,
  game_indices: Array<any>,
  height: number,
  held_items: Array<any>,
  id: number,
  is_default: boolean,
  location_area_encounters: string,
  moves: Array<any>,
  name: string,
  order: number,
  past_types: Array<any>,
  species: any,
  sprites: { back_default: string,
    back_female: any,
    back_shiny: string,
    back_shiny_female: any,
    front_default:string,
    front_female:any,
    front_shiny:string,
    front_shiny_female:any,
    other: { dream_world:{front_default:string,front_female:any},
      home: { front_default:string, front_female: string, front_shiny: string, front_shiny_female: string },
      "official-artwork": {front_default:string}},
    versions:any},
  stats: Array<any>,
  types: Array<{ slot: number, type:{name: string, url:string} }>,
  weight: number,
}
